// initiating the project
var express = require('express');
require('./server.js');
require('./app.js');
var app = express();

// Spotify Web API set up (requires appropriate credentials)
var SpotifyWebApi = require('spotify-web-api-node');
var spotifyApi = new SpotifyWebApi({
    clientId: '6f90aae762534341aac911e306e7fc91',
    scopes: ['user-read-recently-played', 'user-library-read', 'playlist-read-private', 'playlist-read-collaborative', 'user-top-read', 'playlist-modify-public'],
});
// your_mood_playlist is the storage location of the playlist that will be 
// created using the data analysis algorithm. 
var your_mood_playlist = null;
var playlistName = "Your Echo Chamber";

//trackList_uris is a list of the uri values of each track in the playlist.
var trackList_uris = ['spotify:track:4iV5W9uYEdYUVa79Axb7Rh',
    'spotify:track:1301WleyT98MSxVHPZCA6M'];

// Refers to the users individual id 
var userId;

// Refers to the playlists ID, given to a playlist after it is created.
var playlistId;

//---------------- SPOTIFY API CALLS -----------------//
// If a playlist has not yet been created...
if (your_mood_playlist == null) {
    // Create a new playlist, inserting the user ID, playlist ID, and public/private option
    spotifyApi.createPlaylist(userId, playlistName);
    // Add the tracks generated by the statistical algorithm to the playlist.
    spotifyApi.addTracksToPlaylist(your_mood_playlist, trackList_uris);
    if (trackList_uris.length == 0) {
        your_mood_playlist = null;
        console.log("No songs were discovered matching your current mood");
    }
}
// Else if a playlist had already been created previously...
else {
    // Remove the current tracks from the playlist (outdated now)
    spotifyApi.removeTracksFromPlaylist(your_mood_playlist, trackList_uris);
    // Add the new tracks to the playlist (need URI format for the tracks, find a way to convert from the trackID)
    spotifyApi.addTracksToPlaylist(your_mood_playlist, trackList_uris);
}